### ISSUE TITLE
libepoxy crash with AMDGPU-PRO

### ISSUE THREAD

**Issue by LocutusOfBorg** [anholt/libepoxy#130] opened 2017-06-23 09:46 UTC
Hello, I cherry-picked commit 8d58c890646fc1f43bcab702bb9ed6bae94daefe and this caused unbootability of some old proprietary AMD drivers

Can you please enlighten me?
Seems that 1.3.1 with that commit is a no-go, but I'm not sure how this can be solved, and if the revert is doable for you

**Comment by ebassi** [comment] 2017-06-23 10:01
That commit was reverted from the master branch.

Can you try and reproduce with Epoxy 1.4.3, or master?

**Comment by LocutusOfBorg** [comment] 2017-06-23 10:02
I already packaged it and requested to test in the launchpad bug, and damn, I didn't link it here
https://bugs.launchpad.net/ubuntu/+source/libepoxy/+bug/1698233

**Comment by LocutusOfBorg** [comment] 2017-06-23 10:03
I packaged 1.4.3, even if the priority was to trace down the bad patch and revert it, now that I know the bad commit I'll try to understand if master works, and in case
1) cherry-pick subsequent commits to make the old library work too
2) revert the commit and live happy

**Comment by ebassi** [comment] 2017-06-23 10:05
You should either keep libepoxy at 1.3.1 as it was released, or skip all the intermediate commits until 1.4.0. There was a lot of breakage between 1.3.1 and 1.4.0, and no commits in there are suitable for cherry picking.

**Comment by ebassi** [comment] 2017-06-23 10:07
Incidentally, and after reading the bug report on Launchpad: if the goal is to have support for OpenGL 4.5 then you should use libepoxy 1.4. since the GL registry used to generate the entry points was updated to 4.5 for the 1.4.0 release.

**Comment by LocutusOfBorg** [comment] 2017-06-23 10:08
I cherry-picked on top of 1.3.1 only 4 commits, and 3 of them were just NPE checks, the 4th patch is the bad one :)
this is the diff:
http://launchpadlibrarian.net/322881986/libepoxy_1.3.1-1_1.3.1-1ubuntu0.16.04.1.diff.gz

b3b8bd9af7bf1fcfe544fd131f4d4f0d117ae7bc
b8d609e8f9fc1f9c4ff359adb2c1c44619a9e7cf
8d58c890646fc1f43bcab702bb9ed6bae94daefe

**Comment by LocutusOfBorg** [comment] 2017-06-23 10:09
I would like to understand if the bug is really fixed in 1.4+ before checking if it is suitable for an update into an LTS release

**Comment by ebassi** [comment] 2017-06-23 10:11
Sure; that's why I said: either keep 1.3.1 as it is, or jump to 1.4.3. I expect you to test if 1.4.3 fixes the issue, though. ;-)

To be fair, that code does not exist anywhere in the repository, so if adding it breaks something then there's nothing to "be fixed", per se.

**Comment by LocutusOfBorg** [comment] 2017-06-23 21:53
"I tried the version from the new ppa (1.4.3-0ubuntu2) but unfortunately it re-introduced the black screen hang on boot. I reverted to 1.3.1-1 for now."

"I tried the 1.4.3-0ubuntu2 version as well and it also reintroduced the black screen hang on boot for me. I reverted back to 1.3.1-1ubuntu1.16.04.2."

so, it seems that commit has to be reverted in the master branch aswell?

**Comment by ebassi** [comment] 2017-06-24 11:32
The commit you reference has already been reverted, before 1.4.0 was released.

The current code is the result of 91916269e501e041406b092c7242757d0320b802, which is appropriate.

Considering you're using old binary blob drivers, I wouldn't be entirely surprised if it were a case of a driver bug; in any case, you'll have to do some investigative work yourself, given that I don't have the hardware nor the driver to test.

**Comment by LocutusOfBorg** [comment] 2017-06-24 11:45
As said, 1.4.3 is bad too, and since the drivers are proprietary... I don't really know how we can fix that mess.
If you want me to ask people to test stuff, just ask and I will create test builds :)
for now, that commit has been reverted in debian and Ubuntu, and we will update also the stable releases.

**Comment by ebassi** [comment] 2017-06-24 12:32
> If you want me to ask people to test stuff, just ask and I will create test builds :)

I don't have anything to test, really; you need to ask somebody that is experiencing the issue to investigate what's really happening. "A black screen at boot" doesn't tell me much.

Please, ask the reporters to comment on this issue if they want to help getting this fixed.

> for now, that commit has been reverted in debian and Ubuntu, and we will update also the stable releases.

That's a pretty poor handling of the issue. For an LTS release is perfectly acceptable to run on epoxy 1.3.1. For newer releases I'd expect people experiencing the issue to work on it upstream, instead of randomly reverting commits (or randomly cherry picking them).

**Comment by m-ad** [comment] 2017-06-25 21:48
> I don't have anything to test, really; you need to ask somebody that is experiencing the issue to investigate what's really happening. "A black screen at boot" doesn't tell me much.
>
> Please, ask the reporters to comment on this issue if they want to help getting this fixed

Hi, I'm one of the people from the [Launchpad bug](https://bugs.launchpad.net/ubuntu/+source/libepoxy/+bug/1698233) that experience the boot screen hang issue either with the cherry-picked libepoxy 1.3.1 version and with 1.4.3 (for more info see over there). Right know I'm fine with running epoxy 1.3.1, but if you are interested in figuring out where my problem with 1.4.3 comes from I'd be glad to help and run some test if I can. Just tell me what to look for.

**Comment by ebassi** [comment] 2017-07-13 09:55
@m-ad Thanks for your help.

The Launchpad bug is a bit inscrutable to me; the report seems to be related to a black boot — I assume the compositor is not being brought up — but there are no X11 or system logs to show if there's an error. Additionally, [this comment](https://bugs.launchpad.net/ubuntu/+source/libepoxy/+bug/1698233/comments/12) seems to indicate that the latest version does indeed work, but then it leads to brokenness with applications, as opposed to the compositor.

It would be nice if you could rebuild Epoxy from master with https://github.com/anholt/libepoxy/commit/91916269e501e041406b092c7242757d0320b802 reverted, and verify if it works against your AMD driver. It would also be great if you could look into the system logs to see if there are any errors reported there.

Thanks again!

**Comment by LocutusOfBorg** [comment] 2017-07-13 11:41
@m-ad 
I prepared the latest master with that commit reverted, and uploaded in my ppa for testing:
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/locutusofborg-ppa/+sourcepub/8042709/+listing-archive-extra

the build will be done in some hours

**Comment by nwnk** [comment] 2017-07-13 16:42
I'd also be interested in the results of testing git master as well, as of #133 this code is a bit more cautious.

**Comment by LocutusOfBorg** [comment] 2017-07-14 07:12
yeah, that commit is available in the above test build.

**Comment by nwnk** [comment] 2017-07-14 15:02
I meant just master, without the revert of 9191626, as I'm pretty sure it's correct and I'd like to know what amdgpu's libGL is getting wrong.

**Comment by LocutusOfBorg** [comment] 2017-07-14 15:50
so, please @m-ad test also the master without that commit reverted, available here
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/costamagnagianfranco-ppa/+sourcepub/8045607/+listing-archive-extra

**Comment by m-ad** [comment] 2017-07-15 16:14
I tested the first build (1.4.3+git20170713-1~ppa3) and that seems to work just fine. No black screen hang on boot, everything looks okay.

I can't test the second one (1.4.3+git20170713-1~ppa4) as `apt-get` says there are no updates available (yes, I added the PPA). There are build errors mentioned on the PPA's Launchpad page though.

@ebassi Which logs would be of interest and what should I look for? I don't have much experience with bug hunting.

**Comment by LocutusOfBorg** [comment] 2017-07-18 10:36
@m-ad retried them, yes I didn't have debhelper in backports enabled :)

**Comment by m-ad** [comment] 2017-07-18 17:53
1.4.3+git20170713-1~ppa4 gives me the black screen showing only an underscore at boot. I reverted to the previous one for now.

**Comment by LocutusOfBorg** [comment] 2017-07-18 18:11
so, that revert seems needed with current master at e0426c94f6d0b45452d7a5f1b60a0d569be0db47
the revert of 91916269e501e041406b092c7242757d0320b802 seems to be still needed/useful

**Comment by nwnk** [comment] 2018-04-30 20:11
Can you try this branch?

https://github.com/nwnk/libepoxy/tree/even-more-gentle-glx-detection

**Comment by LocutusOfBorg** [comment] 2018-05-14 11:58
@m-ad I used 1.4.3 and cherry-picked/rebased the two commits above (pull #168)

libepoxy - 1.4.3-1ubuntu18.04.1
libepoxy - 1.4.3-1ubuntu16.04.1

are you still available to do a test build in my ppa?
https://launchpad.net/%7Ecostamagnagianfranco/+archive/ubuntu/locutusofborg-ppa/+delete-packages

patch:
```
Index: libepoxy-1.4.3/src/dispatch_common.c
===================================================================
--- libepoxy-1.4.3.orig/src/dispatch_common.c
+++ libepoxy-1.4.3/src/dispatch_common.c
@@ -299,7 +299,11 @@
 #else
     pthread_mutex_lock(&api.mutex);
     if (!*handle) {
-        *handle = dlopen(lib_name, RTLD_LAZY | RTLD_LOCAL);
+        int flags = RTLD_LAZY | RTLD_LOCAL;
+        if (!exit_on_fail)
+            flags |= RTLD_NOLOAD;
+
+        *handle = dlopen(lib_name, flags);
         if (!*handle) {
             if (exit_on_fail) {
                 fprintf(stderr, "Couldn't open %s: %s\n", lib_name, dlerror());
@@ -503,16 +507,9 @@
 #if !PLATFORM_HAS_GLX
     return false;
 #else
-    /* If the application hasn't explicitly called some of our GLX
-     * or EGL code but has presumably set up a context on its own,
-     * then we need to figure out how to getprocaddress anyway.
-     *
-     * If there's a public GetProcAddress loaded in the
-     * application's namespace, then use that.
-     */
     void *sym;
 
-    sym = dlsym(NULL, "glXGetCurrentContext");
+    sym = epoxy_conservative_glx_dlsym("glXGetCurrentContext", false);
     if (sym) {
         if (glXGetCurrentContext())
             return true;
@@ -521,7 +518,7 @@
     }
 
 #if PLATFORM_HAS_EGL
-    sym = dlsym(NULL, "eglGetCurrentContext");
+    sym = epoxy_conservative_egl_dlsym("eglGetCurrentContext", false);
     if (sym) {
         if (epoxy_egl_get_current_gl_context_api() != EGL_NONE)
             return false;
@@ -530,21 +527,6 @@
     }
 #endif /* PLATFORM_HAS_EGL */
 
-    /* OK, couldn't find anything in the app's address space.
-     * Presumably they dlopened with RTLD_LOCAL, which hides it
-     * from us.  Just go dlopen()ing likely libraries and try them.
-     */
-    sym = do_dlsym(&api.glx_handle, GLX_LIB, "glXGetCurrentContext", false);
-    if (sym && glXGetCurrentContext())
-        return true;
-
-#if PLATFORM_HAS_EGL
-    sym = do_dlsym(&api.egl_handle, EGL_LIB, "eglGetCurrentContext",
-                   false);
-    if (sym && epoxy_egl_get_current_gl_context_api() != EGL_NONE)
-        return false;
-#endif /* PLATFORM_HAS_EGL */
-
     return false;
 #endif /* PLATFORM_HAS_GLX */
 }
@@ -730,20 +712,20 @@
 #if PLATFORM_HAS_EGL
     get_dlopen_handle(&api.egl_handle, EGL_LIB, false);
     if (api.egl_handle) {
+        int version = 0;
         switch (epoxy_egl_get_current_gl_context_api()) {
         case EGL_OPENGL_API:
             return epoxy_gl_dlsym(name);
         case EGL_OPENGL_ES_API:
-            /* We can't resolve the GL version, because
-             * epoxy_glGetString() is one of the two things calling
-             * us.  Try the GLES2 implementation first, and fall back
-             * to GLES1 otherwise.
-             */
-            get_dlopen_handle(&api.gles2_handle, GLES2_LIB, false);
-            if (api.gles2_handle)
-                return epoxy_gles2_dlsym(name);
-            else
-                return epoxy_gles1_dlsym(name);
+            if (eglQueryContext(eglGetCurrentDisplay(),
+                                eglGetCurrentContext(),
+                                EGL_CONTEXT_CLIENT_VERSION,
+                                &version)) {
+                if (version >= 2)
+                    return epoxy_gles2_dlsym(name);
+                else
+                    return epoxy_gles1_dlsym(name);
+            }
         }
     }
 #endif /* PLATFORM_HAS_EGL */
```

**Comment by ebassi** [comment] 2018-10-04 23:34
No comment in ~6 months ⇒ closing.

**Closed by ebassi** 2018-10-04 23:34 UTC
Labels: amd, binary driver, linux, question

**Comment by LocutusOfBorg** [comment] 2018-10-05 09:54
sorry, I can't test it, because I lack the hw... @m-ad please ack the changes!

**Comment by m-ad** [comment] 2018-10-06 13:08
Sorry, I can't test this anymore since I updated my kernel and got rid of the proprietary amdgpu-pro driver.
