### ISSUE TITLE
glGetString displays (null) for nvidia-340xx

### ISSUE THREAD

**Issue by wojnilowicz** [anholt/libepoxy#253] opened 2021-05-21 13:24 UTC
Steps to reproduce:
1) unpack [gl3.zip](https://github.com/anholt/libepoxy/files/6522638/gl3.zip)
2) compile gl3.cxx with "cc -o gl3 gl3.cxx -Dwith_epoxy=1 -lGL -lX11 -lepoxy"
3) run "./gl3"

Result:
OpenGL vendor string: (null)

Expected result:
OpenGL vendor string: NVIDIA Corporation

Additional info:
1) compiling gl3.cxx with "cc -o gl3 gl3.cxx -Dwith_epoxy=0 -lGL -lX11 -lepoxy" gives
OpenGL vendor string: NVIDIA Corporation

2) compiling gl3.cxx with "cc -o gl3 gl3.cxx -Dwith_epoxy=1 /usr/lib64/libOpenGL.so /usr/lib64/libGLX.so -lX11 -lepoxy" gives
OpenGL vendor string: (null)

3) compiling gl3.cxx with "cc -o gl3 gl3.cxx -Dwith_epoxy=0 /usr/lib64/libOpenGL.so /usr/lib64/libGLX.so -lX11 -lepoxy" gives
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  37
  Current serial number in output stream:  37

4) reverting https://github.com/anholt/libepoxy/commit/dbfa4b209c0712b67dfeb8366c2ebe8503063b52 helps

5) KDE relies on info returned from glGetString to enable compositing, and after getting (null) for every query, the compositor remains disabled.

6) Fedora 34 X86_64, libepoxy 1.5.7, nvidia 340.108

Please fix this.

**Comment by ebassi** [comment] 2021-05-21 14:29
This is a duplicate of #252.

**Closed by ebassi** 2021-05-21 14:29 UTC

**Comment by ya-isakov** [comment] 2021-05-21 16:00
@wojnilowicz is it the same with `cc -o gl3 gl3.cxx -Dwith_epoxy=1 -lX11 -lepoxy` (just dropped linking with libOpenGL.so and libGLX.so, libepoxy should load them dynamically)

**Comment by ya-isakov** [comment] 2021-05-21 16:05
@wojnilowicz also, could you, please, check if libGLX.so is provided by libglvnd?

**Comment by wojnilowicz** [comment] 2021-05-22 07:45
> @wojnilowicz is it the same with `cc -o gl3 gl3.cxx -Dwith_epoxy=1 -lX11 -lepoxy` (just dropped linking with libOpenGL.so and libGLX.so, libepoxy should load them dynamically)

Yes.

> @wojnilowicz also, could you, please, check if libGLX.so is provided by libglvnd?

Yes.
