### ISSUE TITLE
wglGetProcAdress can't find glGenTextures?

### ISSUE THREAD

**Issue by NickNick** [anholt/libepoxy#67] opened 2015-08-26 20:36 UTC
In my program I have the following code:

``` C++
        init_sdl(fullscreen, wanted_resolution_width, wanted_resolution_height);
        int gl_version = epoxy_gl_version();
        ASDOUT << "Running OpenGL " << gl_version << std::endl;
        epoxy_handle_external_wglMakeCurrent();
        if (verbose) {
            ASDOUT << "Initialization done" << std::endl;
        }
```

... which has the following output when run under wine

```
src/generic_main.hpp: 229(    GenericMain): Running OpenGL 33
src/generic_main.hpp: 235(    GenericMain): Initialization done
warn:wgl:wglGetProcAddress Function glGenTextures unknown
wine: Unhandled page fault on read access to 0x00000000 at address (nil) (thread 0009), starting debugger...
```

So after "initialization done" the rest of the program runs, calls glGenTextures somewhere but that returns 0, crashing the program. What may I be doing wrong in this example? If you need more code or clarification please ask.

Thanks in advance,

**Comment by NickNick** [comment] 2015-08-27 18:16
For easy reproduction, `git clone --recursive https://github.com/NickNick/mxesdlepoxy` and build with MXE.

**Comment by yaronct** [comment] 2015-08-27 20:12
@NickNick: Can u reproduce the issue without Wine? (Perhaps in real Windows?) Running stuff in Wine is problematic in general, and I wouldn't wanna start debugging in Wine.

**Comment by Nephatrine** [comment] 2015-08-30 02:00
@NickNick - I tested with with my libepoxy build in Windows and it works just fine assuming it is supposed to be a program to induce seizures due to rapid color flashes. I do not suggest maximizing it to fullscreen and staring for any length of time.

**Comment by NickNick** [comment] 2015-08-30 09:32
They work, it's not a static build. Perhaps that's the problem? Do I need to take some steps for static builds?

**Comment by Nephatrine** [comment] 2015-08-30 15:45
@NickNick - Yes, that is exactly your problem. Epoxy does some magic in DLLMain that isn't initialized in a static build since those don't call DLLMain. [My fork](https://github.com/Nephatrine/libepoxy) does properly work with static builds on Windws 7 and 8 (haven't tested elsewhere). Just call cmake with ```-DBUILD_SHARED_LIBS=OFF``` and it will build the static library.

**Comment by ebassi** [comment] 2017-02-03 15:25
@Nephatrine Could you submit a PR for the static build fix, so I can review it?

**Comment by ebassi** [comment] 2020-01-14 12:09
Nothing happened in 3 years ⇒ closing

Epoxy uses Meson, now, and it does support static builds: I can successfully do a static build on Linux. If static builds on Windows fail, they should be reported as a separate issue.

**Closed by ebassi** 2020-01-14 12:09 UTC
Labels: build, question, windows
